### ISSUE TITLE
instrument: deferrable API

### ISSUE THREAD

**Issue by mmcloughlin** [uber-go/tally#143]
I have found that using the callback-based API provided by `instrument` can be awkward, especially when the function being instrumented returns a value other than an error. It either forces the body of the function to be indented one more level, or you have to put the function body in a second function called from the instrument callback. When the instrumented function returns some value, you have to do some delicate gymnastics to ensure the return value is assigned to a variable in the closure.

I propose adding a deferrable API to the `instrument` package, so it could be used something like:

```go
func (s *Struct) Method() (_ *Result, err error) {
	defer instrument.Function(s.scope, "method", &err)()
	// ...
}
```

This has the benefit that the instrumented function is minimally altered, besides the `defer` line and the named `err` return. I'm not sure `instrument.Function` is a good name, that's up for debate.

Alternatively, instead of a top-level function in the `instrument` package, we could add a second method to the `Call` struct with a similar API.

I'd be happy to prepare a PR if you think this is a good idea.

**Comment by mway** [comment]
Hey @mmcloughlin!

A few things come to mind: first, that the `instrument` package would probably be better as an internal package in order to conventionalize/standardize golden signals; second, that existing Go contructs, like [errgroup](https://godoc.org/golang.org/x/sync/errgroup), have a similar shape (`func() error`), so this seems to be a reasonable generalization and is based on the minimum information required (call time and errors) to perform its function; and third, that the upcoming redesign of Tally will probably not include this functionality out of the box.

Considering all of that, it's probably not super valuable to invest in the `instrument` API right now. Sorry!

Definitely happy to chat more about it if you'd like - just reach out.

**Comment by mmcloughlin** [comment]
Hey @mway!

I have a PR out for an `instrument` package at Uber ATG with an API similar to my proposal here. The exact API is still under debate. That said, this is an extremely common use case, so I think it's reasonable for `tally` to have an `instrument` package (and for the redesign to have one too). Just my 2 cents.

I'm not sure I agree the comparison with `errgroup` is reasonable. I'm not against function arguments in APIs in general, I'd just claim it's awkward in the `instrument` use case. In particular, the `errgroup` API is natural since it's nearly a drop-in replacement for `sync.WaitGroup`. In these use cases you would likely have a construct like `go func() { ... }()` anyway, so changing it to `g.Go(func() error { ... })` doesn't impose any extra burden. In contrast, the current `call.Exec(...)` API forces you introduce an extra anonymous function where you didn't have one before. I believe some deferrable API would be less invasive.
