### ISSUE TITLE
Tally should not pin any dependencies to hashes in glide.yaml

### ISSUE THREAD

**Issue by prashantv** [uber-go/tally#82]
Currently, tally has many pins to hashes in the `glide.yaml` file:

E.g.,
```
- package: github.com/m3db/prometheus_client_golang
  version: 8ae269d24972b8695572fa6b2e3718b5ea82d6b4
```

```
- package: github.com/apache/thrift
  version: 9549b25c77587b29be4e0b5c258221a4ed85d37a
```

These are problematic for a few reasons:
 * It's not clear what API surface tally is pinning to, as it's not using a semver pin
 * It's very rigid, and likely to cause problems with another package that uses the same dependency, as they're unlikely to agree on the same hash
 * Dep ignores pins to specific revisions (Dep logs: `Ignoring pinned constraint 9549b25c77587b29be4e0b5c258221a4ed85d37a for github.com/apache/thrift." when importing uber-go/tally.`)

This causes problems for users as we migrate to dep, as the Tally constraints are ignored, and users end up getting the latest version of some dependencies (e.g., Thrift) which are not compatible (as they have a `ctx` parameter).

Can we ensure all non-test dependencies are pinned to version ranges where possible?

**Comment by robskillington** [comment]
Honestly we don't care either way, we actually found pinning to hashes to be much less problematic with glide because it didn't try to strictly apply semver and was more relaxed (created less problems when trying to find a mutual version to select when conflicts were found between two dependencies using tally).

More than happy to move them to pinned ranges, I'd want to make sure our repositories can actually build with more strict ranges applied though before we actually merge to master.

**Comment by robskillington** [comment]
We ended up pinning the remaining dependencies.

**Comment by prashantv** [comment]
Perfect, thanks!
